# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20160118_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStageQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_one', models.ManyToManyField(default=None, related_name='part_one', to='questions.SimpleQuestion')),
                ('part_two', models.ManyToManyField(default=None, related_name='part_two', to='questions.SimpleQuestion')),
            ],
        ),
        migrations.AlterField(
            model_name='dayscore',
            name='date',
            field=models.DateField(default=datetime.date(2016, 2, 3)),
        ),
    ]
