# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20160203_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistagequestion',
            name='part_five',
            field=models.ManyToManyField(default=None, related_name='part_five', to='questions.SimpleQuestion'),
        ),
        migrations.AddField(
            model_name='multistagequestion',
            name='part_four',
            field=models.ManyToManyField(default=None, related_name='part_four', to='questions.SimpleQuestion'),
        ),
        migrations.AddField(
            model_name='multistagequestion',
            name='part_three',
            field=models.ManyToManyField(default=None, related_name='part_thre', to='questions.SimpleQuestion'),
        ),
    ]
