# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20160211_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistagequestion',
            name='InterTextFour',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='InterTextOne',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='InterTextThree',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='InterTextTwo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='part_five',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_five', to='questions.SimpleQuestion'),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='part_four',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_four', to='questions.SimpleQuestion'),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='part_one',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_one', to='questions.SimpleQuestion'),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='part_three',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_three', to='questions.SimpleQuestion'),
        ),
        migrations.AlterField(
            model_name='multistagequestion',
            name='part_two',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_two', to='questions.SimpleQuestion'),
        ),
    ]
