# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20160211_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multistagequestion',
            old_name='InterTextOne',
            new_name='InterText1',
        ),
        migrations.RenameField(
            model_name='multistagequestion',
            old_name='InterTextTwo',
            new_name='InterText2',
        ),
        migrations.RenameField(
            model_name='multistagequestion',
            old_name='InterTextThree',
            new_name='InterText3',
        ),
        migrations.RenameField(
            model_name='multistagequestion',
            old_name='InterTextFour',
            new_name='InterText4',
        ),
        migrations.RemoveField(
            model_name='multistagequestion',
            name='part_five',
        ),
        migrations.RemoveField(
            model_name='multistagequestion',
            name='part_four',
        ),
        migrations.RemoveField(
            model_name='multistagequestion',
            name='part_one',
        ),
        migrations.RemoveField(
            model_name='multistagequestion',
            name='part_three',
        ),
        migrations.RemoveField(
            model_name='multistagequestion',
            name='part_two',
        ),
        migrations.AddField(
            model_name='multistagequestion',
            name='part_1',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_1', to='questions.SimpleQuestion'),
        ),
        migrations.AddField(
            model_name='multistagequestion',
            name='part_2',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_2', to='questions.SimpleQuestion'),
        ),
        migrations.AddField(
            model_name='multistagequestion',
            name='part_3',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_3', to='questions.SimpleQuestion'),
        ),
        migrations.AddField(
            model_name='multistagequestion',
            name='part_4',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_4', to='questions.SimpleQuestion'),
        ),
        migrations.AddField(
            model_name='multistagequestion',
            name='part_5',
            field=models.ManyToManyField(blank=True, default=None, related_name='part_5', to='questions.SimpleQuestion'),
        ),
        migrations.AlterField(
            model_name='dayscore',
            name='date',
            field=models.DateField(default=datetime.date(2016, 2, 13)),
        ),
    ]
